# Generated by Django 5.0.4 on 2024-05-26 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('name', models.CharField(help_text='Category name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('username', models.CharField(help_text='Client username', max_length=30, unique=True)),
                ('email', models.EmailField(help_text='Client email', max_length=50, unique=True)),
                ('phone', models.CharField(help_text='Client phone number', max_length=13, unique=True)),
                ('password', models.CharField(help_text='Client password', max_length=50)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('username', models.CharField(help_text='Client username', max_length=30, unique=True)),
                ('email', models.EmailField(help_text='Client email', max_length=50, unique=True)),
                ('phone', models.CharField(help_text='Client phone number', max_length=13, unique=True)),
                ('password', models.CharField(help_text='Client password', max_length=50)),
                ('position', models.CharField(help_text='Employee position', max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Employee salary', max_digits=10)),
                ('photo', models.ImageField(help_text='Employee photo', upload_to='zoo_shop_app/static/employees')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('name', models.CharField(help_text='Supplier name', max_length=30)),
                ('country', models.CharField(help_text='Supplier country', max_length=30)),
                ('phone', models.CharField(help_text='Supplier phone number', max_length=13, unique=True)),
                ('email', models.EmailField(help_text='Supplier email', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('article', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Product name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('image', models.ImageField(help_text='Product image', upload_to='zoo_shop_app/static/products')),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, to='zoo_shop_app.category')),
                ('supplier', models.ForeignKey(help_text='Product supplier', on_delete=django.db.models.deletion.CASCADE, to='zoo_shop_app.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(help_text='Unique id', primary_key=True, serialize=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, help_text='Update date')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost', max_digits=10)),
                ('address', models.CharField(default='Minsk, Gikalo 9', help_text='Sale address', max_length=100)),
                ('client', models.ForeignKey(help_text='Client who made the order', on_delete=django.db.models.deletion.CASCADE, to='zoo_shop_app.client')),
                ('products', models.ManyToManyField(help_text='List of bought products', to='zoo_shop_app.product')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['create'],
            },
        ),
    ]
