# Generated by Django 5.0.4 on 2024-05-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0003_aboutshop_faq_news_promocode_vacancy_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='aboutshop',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='promocode',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='regularclient',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='regularclient',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='create',
            new_name='created',
        ),
    ]
