# Generated by Django 5.0.4 on 2024-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0004_alter_faq_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Monthly salary', max_digits=10),
        ),
    ]
