# Generated by Django 5.0.4 on 2024-05-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0005_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Article image', upload_to='zoo_shop_app/static/news'),
        ),
    ]
