# Generated by Django 5.0.4 on 2024-05-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0007_alter_client_email_alter_client_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='promocode',
            new_name='code',
        ),
        migrations.AlterModelTable(
            name='promocode',
            table='promocodes',
        ),
    ]
