# Generated by Django 5.0.4 on 2024-05-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0010_remove_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReg',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoo_shop_app.employee')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employees_reg',
                'ordering': ['username'],
            },
            bases=('zoo_shop_app.employee',),
        ),
    ]
