# Generated by Django 5.0.4 on 2024-05-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0012_alter_employee_options_rename_username_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeuser',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
