# Generated by Django 5.0.4 on 2024-05-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0013_rename_employee_id_employeeuser_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
    ]
