# Generated by Django 5.0.4 on 2024-05-28 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0015_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
