# Generated by Django 5.0.4 on 2024-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0019_alter_employee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='text',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
