# Generated by Django 5.0.4 on 2024-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0020_remove_faq_text_remove_faq_title_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=255),
        ),
    ]
