# Generated by Django 5.0.4 on 2024-05-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0022_alter_aboutshop_created_alter_aboutshop_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutshop',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='zoo_shop_app/static/main/user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='zoo_shop_app/static/main/user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='zoo_shop_app/static/main/news.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='zoo_shop_app/static/main/empty.jpg', upload_to=''),
        ),
    ]
