# Generated by Django 5.0.4 on 2024-05-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0023_alter_aboutshop_image_alter_client_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='static/main/user.png', upload_to=''),
        ),
    ]
