# Generated by Django 5.0.4 on 2024-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0024_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='zoo_shop_app/static/main/user.png', upload_to=''),
        ),
    ]
