# Generated by Django 5.0.4 on 2024-05-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0027_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
