# Generated by Django 5.0.4 on 2024-05-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0028_shoppingcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo_shop_app.promocode'),
        ),
    ]
