# Generated by Django 5.0.4 on 2024-05-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0029_sales_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='promocode',
        ),
    ]
