# Generated by Django 5.0.4 on 2024-10-21 14:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0030_remove_sales_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutshop',
            name='image',
            field=models.ImageField(upload_to='main/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 10, 26), message='You must be at least 18 years old to register')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='main/user.png', upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2006, 10, 26), message='You must be at least 18 years old to register')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='main/user.png', upload_to='employees/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='main/news.png', upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='main/empty.jpg', upload_to='products/'),
        ),
    ]
