# Generated by Django 5.0.4 on 2024-10-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0031_alter_aboutshop_image_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='main/user.png', upload_to='static/employees/'),
        ),
    ]
