# Generated by Django 5.0.4 on 2024-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0033_alter_aboutshop_image_alter_client_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='static/main/user.png', upload_to='static/employees/'),
        ),
    ]
