# Generated by Django 5.0.4 on 2024-10-22 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_shop_app', '0035_alter_client_birth_date_alter_employee_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='static/partners/')),
                ('website', models.URLField()),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['name'],
            },
        ),
    ]
